# This is a basic workflow to help you get started with Actions

name: Generate Doxygen documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
      - "main"
      - "RMSW-13" 
  pull_request:
    branches:
    - "main"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "generate-docs"
  generate-docs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Update and install doxygen if it isn't there already
      - name: Update package lists
        run: sudo apt-get update

      - name: Install Doxygen if not installed
        run: |
          if ! command -v doxygen &> /dev/null
          then
              echo "Doxygen not found. Installing..."
              sudo apt-get install -y doxygen graphviz
          else
              echo "Doxygen is already installed."
          fi
          
      - name: Set up Doxygen
        uses: mattnotmitt/doxygen-action@v1.9.5

      - name: Generate Doxygen documentation
        run: |
          doxygen -d WARNING Doxyfile || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./Docs
